// Static species fallback list for the kiosk.
//
// Source of truth: `.kiro/specs/kiosk-redesign/content-source.md` -> "9. Data Spesies".
// This list is used when `/api/kiosk/species` returns no data (Req 14.1, 16.4) so the
// Data Spesies and Virtual Insektarium screens always have something to render.
//
// Families are the CORRECTED taxonomy from content-source.md (Papilionidae / Pieridae /
// Nymphalidae / Lycaenidae) - NOT the misspelled "PAPILIONIDE"/"LYKANIDE" in the original
// document. Rows 7–12 are biologically Pieridae even though the source table grouped them
// under PAPILIONIDE.
//
// Photos live under `public/kiosk/species/<slug>-top.webp` and `<slug>-under.webp`
// (organized from the "Asset foto" delivery). Species without a delivered photo keep null.

import type { KioskSpecies } from "../lib/speciesMapping";

const SPECIES_BASE = "/kiosk/species";

export const STATIC_SPECIES: KioskSpecies[] = [
  {
    id: 1,
    commonName: "Graphium agamemnon",
    scientificName: "Graphium agamemnon",
    family: "Papilionidae",
    genus: "Graphium",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/graphium-agamemnon-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/graphium-agamemnon-under.webp`,
    galleryUrls: [],
  },
  {
    id: 2,
    commonName: "Graphium doson",
    scientificName: "Graphium doson",
    family: "Papilionidae",
    genus: "Graphium",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/graphium-doson-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/graphium-doson-under.webp`,
    galleryUrls: [],
  },
  {
    id: 3,
    commonName: "Graphium sarpedon",
    scientificName: "Graphium sarpedon",
    family: "Papilionidae",
    genus: "Graphium",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/graphium-sarpedon-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/graphium-sarpedon-under.webp`,
    galleryUrls: [],
  },
  {
    id: 4,
    commonName: "Papilio demoleus",
    scientificName: "Papilio demoleus",
    family: "Papilionidae",
    genus: "Papilio",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/papilio-demoleus-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/papilio-demoleus-under.webp`,
    galleryUrls: [],
  },
  {
    id: 5,
    commonName: "Papilio memnon",
    scientificName: "Papilio memnon",
    family: "Papilionidae",
    genus: "Papilio",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/papilio-memnon-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/papilio-memnon-under.webp`,
    galleryUrls: [],
  },
  {
    id: 6,
    commonName: "Papilio polytes",
    scientificName: "Papilio polytes",
    family: "Papilionidae",
    genus: "Papilio",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/papilio-polytes-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/papilio-polytes-under.webp`,
    galleryUrls: [],
  },
  {
    id: 7,
    commonName: "Appias olferna (Jantan/Male)",
    scientificName: "Appias olferna",
    family: "Pieridae",
    genus: "Appias",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/appias-olferna-jantan-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/appias-olferna-jantan-under.webp`,
    galleryUrls: [],
  },
  {
    id: 8,
    commonName: "Appias olferna (Betina/Female)",
    scientificName: "Appias olferna",
    family: "Pieridae",
    genus: "Appias",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/appias-olferna-betina-top.webp`,
    undersidePhotoUrl: null,
    galleryUrls: [],
  },
  {
    id: 9,
    commonName: "Delias hyparete",
    scientificName: "Delias hyparete",
    family: "Pieridae",
    genus: "Delias",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/delias-hyparete-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/delias-hyparete-under.webp`,
    galleryUrls: [],
  },
  {
    id: 10,
    commonName: "Eurema blanda",
    scientificName: "Eurema blanda",
    family: "Pieridae",
    genus: "Eurema",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/eurema-blanda-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/eurema-blanda-under.webp`,
    galleryUrls: [],
  },
  {
    id: 11,
    commonName: "Catopsilia pyranthe",
    scientificName: "Catopsilia pyranthe",
    family: "Pieridae",
    genus: "Catopsilia",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/catopsilia-pyranthe-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/catopsilia-pyranthe-under.webp`,
    galleryUrls: [],
  },
  {
    id: 12,
    commonName: "Leptosia nina",
    scientificName: "Leptosia nina",
    family: "Pieridae",
    genus: "Leptosia",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/leptosia-nina-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/leptosia-nina-under.webp`,
    galleryUrls: [],
  },
  {
    id: 13,
    commonName: "Acraea terpsicore",
    scientificName: "Acraea terpsicore",
    family: "Nymphalidae",
    genus: "Acraea",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/acraea-terpsicore-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/acraea-terpsicore-under.webp`,
    galleryUrls: [],
  },
  {
    id: 14,
    commonName: "Junonia orithya (Jantan/Male)",
    scientificName: "Junonia orithya",
    family: "Nymphalidae",
    genus: "Junonia",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/junonia-orithya-jantan-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/junonia-orithya-jantan-under.webp`,
    galleryUrls: [],
  },
  {
    id: 15,
    commonName: "Junonia orithya (Betina/Female)",
    scientificName: "Junonia orithya",
    family: "Nymphalidae",
    genus: "Junonia",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/junonia-orithya-betina-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/junonia-orithya-betina-under.webp`,
    galleryUrls: [],
  },
  {
    id: 16,
    commonName: "Neptis hylas",
    scientificName: "Neptis hylas",
    family: "Nymphalidae",
    genus: "Neptis",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/neptis-hylas-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/neptis-hylas-under.webp`,
    galleryUrls: [],
  },
  {
    id: 17,
    commonName: "Hypolimnas missipus (Jantan/Male)",
    scientificName: "Hypolimnas missipus",
    family: "Nymphalidae",
    genus: "Hypolimnas",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/hypolimnas-missipus-jantan-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/hypolimnas-missipus-jantan-under.webp`,
    galleryUrls: [],
  },
  {
    id: 18,
    commonName: "Hypolimnas missipus (Betina/Female)",
    scientificName: "Hypolimnas missipus",
    family: "Nymphalidae",
    genus: "Hypolimnas",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/hypolimnas-missipus-betina-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/hypolimnas-missipus-betina-under.webp`,
    galleryUrls: [],
  },
  {
    id: 19,
    commonName: "Doleschallia bisaltide",
    scientificName: "Doleschallia bisaltide",
    family: "Nymphalidae",
    genus: "Doleschallia",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/doleschallia-bisaltide-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/doleschallia-bisaltide-under.webp`,
    galleryUrls: [],
  },
  {
    id: 20,
    commonName: "Euploea leucostictos",
    scientificName: "Euploea leucostictos",
    family: "Nymphalidae",
    genus: "Euploea",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/euploea-leucostictos-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/euploea-leucostictos-under.webp`,
    galleryUrls: [],
  },
  {
    id: 21,
    commonName: "Hypolimnas bolina (Jantan/Male)",
    scientificName: "Hypolimnas bolina",
    family: "Nymphalidae",
    genus: "Hypolimnas",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/hypolimnas-bolina-jantan-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/hypolimnas-bolina-jantan-under.webp`,
    galleryUrls: [],
  },
  {
    id: 22,
    commonName: "Hypolimnas bolina (Betina/Female)",
    scientificName: "Hypolimnas bolina",
    family: "Nymphalidae",
    genus: "Hypolimnas",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/hypolimnas-bolina-betina-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/hypolimnas-bolina-betina-under.webp`,
    galleryUrls: [],
  },
  {
    id: 23,
    commonName: "Melanitis leda",
    scientificName: "Melanitis leda",
    family: "Nymphalidae",
    genus: "Melanitis",
    iucnStatus: "Least Concern",
    topPhotoUrl: `${SPECIES_BASE}/melanitis-leda-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/melanitis-leda-under.webp`,
    galleryUrls: [],
  },
  {
    id: 24,
    commonName: "Junonia iphita",
    scientificName: "Junonia iphita",
    family: "Nymphalidae",
    genus: "Junonia",
    iucnStatus: null,
    topPhotoUrl: `${SPECIES_BASE}/junonia-iphita-top.webp`,
    undersidePhotoUrl: `${SPECIES_BASE}/junonia-iphita-under.webp`,
    galleryUrls: [],
  },
  {
    id: 25,
    commonName: "Zizina otis",
    scientificName: "Zizina otis",
    family: "Lycaenidae",
    genus: "Zizina",
    iucnStatus: null,
    topPhotoUrl: null,
    undersidePhotoUrl: null,
    galleryUrls: [],
  },
];
